name: pylint

on:
  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-18.04
    steps:
    - name: Check out code
      uses: actions/checkout@v1
      with:
        fetch-depth: 1 # Latest commit only
    - name: Setup python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install -r requirements.txt
    - name: Run pylint
      run: | # 'shopt -s globstar' enables use of '**/*'
        shopt -s globstar
        pylint **/*.py
